name: build

on:
  push:
    branches:
      - master

  pull_request:


jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: ./test_ww
